# Generated by Django 4.1.2 on 2022-11-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosanfibio',
            name='urlFoto',
            field=models.CharField(default='', max_length=512),
        ),
    ]
