# Generated by Django 4.1.2 on 2022-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0002_usuariosanfibio_urlfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosanfibio',
            name='usuario',
            field=models.CharField(default='', max_length=64),
        ),
    ]
