# Generated by Django 4.1.3 on 2022-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0004_botesanfibio'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotosAnfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoFoto', models.CharField(default='', max_length=128)),
                ('urlFoto', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
