# Generated by Django 4.1.3 on 2022-12-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0005_fotosanfibio'),
    ]

    operations = [
        migrations.CreateModel(
            name='inspecctionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInspeccion', models.CharField(default='', max_length=128)),
                ('distancia', models.CharField(default='', max_length=128)),
                ('duracion', models.CharField(default='', max_length=128)),
                ('codigoBote', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
