# Generated by Django 4.1.4 on 2022-12-22 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0008_fotosinspeccioninformacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionmultimediadatos',
            name='fechaInspeccion',
            field=models.CharField(default=datetime.datetime(2022, 12, 22, 20, 27, 10, 530091), max_length=128),
        ),
    ]
